djangoproj/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("projekt.urls"))
]

projekt/urls.py
from django.urls import path
from . import views
from django.http import HttpResponse
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('superadmin/',views.admin_home,name='super'),
    path('student/',views.stud_home,name='student'),   
    path('profesor/',views.prof_home,name='profesor'),
    path('', views.home,name="home"),
    path('login/',auth_views.LoginView.as_view(template_name='projekti/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='projekti/logout.html'),name='logout'),
    path('super/adduser',views.adduser,name='adduser'),
    path('super/professors',views.professors,name='professors'),
    path('super/students',views.students,name='students'),
    path('super/addpred',views.addpredmet,name='addpred'),
    path('super/predmet',views.predmeti,name='predmeti'),
    path('super/edituser/<str:pk>/',views.edituser,name='edituser'),
    path('super/editpredmet/<str:pk>/',views.editpredmet,name='editpredmet'),
    path('super/addupis/<str:student_id>/',views.upis_studenta,name='addupis'),
    path('super/students/upisi/<str:pk>/',views.listupis,name='upis'),
    path('super/students/upisi/editupis/<str:pk>/',views.change_upis,name='editupis'),
    path('super/predmeti/liststud/<str:pk>/',views.list_users_per_predmet,name='studpred'),
    path('profesor/profpred',views.listpredmet,name='profpred'),
    path('profesor/profpred/<str:pk>',views.liststud,name='seestud'),
    path('profesor/profpred/upis/<str:pk>/<str:fk>/',views.changestatus,name='editupis'),
    path('student/predstud/',views.listpred,name='predstud'),
    path('student/addupis/<str:pk>',views.add_upis_student,name='addupisstud'),
    path('student/seeupisi/',views.current_upisi,name='seeupis'),
    path('upis/delete/<int:upis_id>/', views.delete_upis, name='delete_upis'),
    path('super/<int:pk>/delete/', views.delete_user, name='delete_user'),
    
]

projekt/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Korisnik(AbstractUser):
    ROLES = (('prof', 'profesor'), ('stu', 'student'),('adm','admin'))
    STATUS = (('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student'))
    role = models.CharField(max_length=50, choices=ROLES)
    status = models.CharField(max_length=50, choices=STATUS)

    

class Predmeti(models.Model):
    IZBORNI = (('DA', 'da'), ('NE', 'ne'))
    name = models.CharField(max_length=50)
    kod = models.CharField(max_length=50)
    program = models.CharField(max_length=50)
    ects = models.IntegerField()
    sem_red = models.IntegerField()
    sem_izv = models.IntegerField()
    izborni = models.CharField(max_length=50, choices=IZBORNI)
    nositelj =models.ForeignKey(Korisnik,on_delete=models.CASCADE, blank=True,null=True)   

    def __str__(self):
        return self.name
    def delete(self,*args,**kwargs):
        self.address.delete()
        super().delete(*args,**kwargs)

class Upisi(models.Model):
    STATUS = (('up', 'upisan'), ('pass', 'polozen'), ('fail', 'izgubio potpis'))
    user_id = models.ForeignKey(Korisnik, on_delete = models.CASCADE,blank=True,null=True)
    predmet_id = models.ForeignKey(Predmeti, on_delete = models.CASCADE, blank=True,null=True)
    status = models.CharField(default='up',max_length=50, choices=STATUS)
    

projekt/forms.py
from .models import Korisnik,Predmeti,Upisi
from django.forms import CharField,PasswordInput
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

class UserForm(forms.ModelForm):
    class Meta:
        model=Korisnik
        fields=['username','role']

class addUserForm(forms.ModelForm):
    password = CharField(widget=PasswordInput())
    
    class Meta:
        model=Korisnik
        fields=['username','email', 'first_name', 'last_name','password','role']
class UserChangeForm(forms.ModelForm):
    
    class Meta:
        model = Korisnik
        fields = ('username', 'email', 'first_name', 'last_name')

class PredmetForm(forms.ModelForm):
    class Meta:
        model = Predmeti
        fields = ['name', 'kod', 'program', 'ects', 'sem_red', 'sem_izv', 'izborni', 'nositelj']

    def __init__(self, *args, **kwargs):
        super(PredmetForm, self).__init__(*args, **kwargs)
        self.fields['nositelj'].queryset = Korisnik.objects.filter(role='prof')

class changePredmetForm(forms.ModelForm):
    class Meta:
        model = Predmeti
        fields=('name', 'kod','nositelj')
    def __init__(self, *args, **kwargs):
        super(changePredmetForm, self).__init__(*args, **kwargs)
        self.fields['nositelj'].queryset = Korisnik.objects.filter(role='prof')

class UpisForm(forms.ModelForm):
    class Meta:
        model = Upisi
        fields = ['user_id', 'predmet_id','status']

    def __init__(self, *args, **kwargs):
        super(UpisForm, self).__init__(*args, **kwargs)
        
class changeUpisForm(forms.ModelForm):
    class Meta:
        model = Upisi
        fields = ['user_id','predmet_id', 'status']

    def __init__(self, *args, **kwargs):
        super(changeUpisForm, self).__init__(*args, **kwargs)
        self.fields['user_id'].disabled = True

class profUpisiForm(forms.ModelForm):
    class Meta:
        model = Upisi
        fields = ['status']

projekt/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth.hashers import make_password
from django.core.paginator import Paginator
from django.db import models
from django.contrib import messages
from .models import *
from django.db.models import Q

def home(request):
    current_user = request.user
    if  current_user.is_authenticated:    
         if current_user.role=='adm':
             return redirect('super')
         elif current_user.role=='stu':
             return redirect('student')
         elif current_user.role=='prof':
             return redirect('profesor')
    else:
        return render(request,'projekti/home.html')

@login_required
def admin_home(request):
    current_user = request.user
    if current_user.role=='adm':
        return render(request,'projekti/admin.html',{'user':current_user})
def stud_home(request):
    current_user = request.user
    if current_user.role=='stu':
        return render(request,'projekti/student.html',{'user':current_user})
def prof_home(request):
    current_user = request.user
    if current_user.role=='prof':
        return render(request,'projekti/profesor.html',{'user':current_user})

def adduser(request):
    if request.method=='POST':
         ap_form=addUserForm(request.POST)
         if ap_form.is_valid():
            first_name = ap_form.cleaned_data['username']
            passw = make_password(ap_form.cleaned_data['password'])
            stat = ap_form.cleaned_data['role']
            user=Korisnik(username=first_name, password=passw, role=stat)
            user.save()
            username=ap_form.cleaned_data.get('username')
            messages.success(request,f'User  {username} created !')
            return redirect('home')
    else:
        ap_form=addUserForm()
    context={'ap_form':ap_form,}   
    return render(request,'projekti/adduser.html',context)

def edituser(request,pk):
    user=Korisnik.objects.get(id=pk)
    eu_form=UserChangeForm(instance=user)
    if request.method=='POST':
         eu_form=UserChangeForm(request.POST,instance=user)
         if eu_form.is_valid():
            eu_form.save()
            username=eu_form.cleaned_data.get('username')
            messages.success(request,f'User  {username} updated !')
            return redirect('home')
    context={'eu_form':eu_form,
    }
    return render(request,'projekti/edituser.html',context)

def editpredmet(request,pk):
    predmet=Predmeti.objects.get(id=pk)
    eu_form=changePredmetForm(instance=predmet)
    if request.method=='POST':
         eu_form=changePredmetForm(request.POST,instance=predmet)
         if eu_form.is_valid():
            eu_form.save()
            name=eu_form.cleaned_data.get('name')
            messages.success(request,f'User  {name} updated !')
            return redirect('home')
    context={'eu_form':eu_form,
    }
    return render(request,'projekti/editpredmet.html',context)

def professors(request):
    professors = Korisnik.objects.filter(role='prof')
    context = {'professors': professors}
    return render(request, 'projekti/professors.html', context)

def students(request):
    students=Korisnik.objects.filter(role='stu')
    context={'students': students}
    return render(request,'projekti/students.html',context)

def predmeti(request):
    predmeti=Predmeti.objects.all()
    context={'predmeti': predmeti}
    return render(request,'projekti/predmeti.html',context)

def addpredmet(request):
    if request.method=='POST':
         p_form=PredmetForm(request.POST)
         if p_form.is_valid():
            p_name = p_form.cleaned_data ['name']
            p_kod = p_form.cleaned_data['kod']
            p_program =p_form.cleaned_data['program']
            p_ects = p_form.cleaned_data['ects']
            p_sem_red =p_form.cleaned_data['sem_red']
            p_sem_izv =p_form.cleaned_data['sem_izv']
            p_izborni =p_form.cleaned_data['izborni']
            p_nositelj =p_form.cleaned_data['nositelj']
            predmet=Predmeti(name=p_name,
                            kod=p_kod,
                            program=p_program,
                            ects=p_ects,
                            sem_red=p_sem_red,
                            sem_izv=p_sem_izv,
                            izborni=p_izborni,
                            nositelj=p_nositelj)
            predmet.save()
            predmet=p_form.cleaned_data.get('name')
            messages.success(request,f'Predmet {p_name} created !')
            return redirect('home')
    else:
        p_form=PredmetForm()
    context={'p_form':p_form,}   
    return render(request,'projekti/addpredmet.html',context)

def addupis(request, pk):
    user = Korisnik.objects.get(id=pk)
    if request.method == 'POST':
        ap_form = UpisForm(request.POST)
        if ap_form.is_valid():
            upis = ap_form.save(commit=False)
            passw =ap_form.cleaned_data['predmet_id']
            stat = ap_form.cleaned_data['status']
            upis = Upisi(user_id=user, predmet_id=passw, status=stat)
            upis.save()
            return redirect('home')
    else:
        
        initial_data = {'user_id': user.id}
        ap_form = UpisForm(initial=initial_data)
        ap_form.fields['user_id'].disabled = True
    context = {'ap_form': ap_form}
    return render(request, 'projekti/addupis.html', context)

def listupis(request,pk):
    user = Korisnik.objects.get(id=pk)
    upisi=Upisi.objects.filter(user_id=user.id)
    context={'upisi': upisi}
    return render(request,'projekti/upisi.html',context)

def change_upis(request, pk):
    upis = Upisi.objects.get(id=pk)
    if request.method == 'POST':
        form = changeUpisForm(request.POST, instance=upis)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = changeUpisForm(instance=upis)
    context = {'form': form}
    return render(request, 'projekti/editupis.html', context)

def list_users_per_predmet(request, pk):
    predmet = Predmeti.objects.get(id=pk)
    users = predmet.upisi_set.all().values('user_id__username')
    context = {'predmet': predmet, 'users': users}
    return render(request, 'projekti/liststud.html', context)

def listpredmet(request):
    user = request.user
    predmeti = Predmeti.objects.filter(nositelj=user)
    context = {'predmeti': predmeti}
    return render(request, 'projekti/profpred.html', context)

def liststud(request,pk):
    predmet = Predmeti.objects.get(id=pk)
    izgubili_potpis = Upisi.objects.filter(predmet_id=predmet, status='fail')
    dobili_potpis = Upisi.objects.filter(predmet_id=predmet, status='up')
    polozili_predmet = Upisi.objects.filter(predmet_id=predmet, status='pass')
    context = {
        'predmet': predmet,
        'izgubili_potpis': izgubili_potpis,
        'dobili_potpis': dobili_potpis,
        'polozili_predmet': polozili_predmet
    }
    return render(request, 'projekti/studpred.html', context)

def changestatus(request,pk,fk):
    user = Korisnik.objects.get(username=pk)
    upisi=Upisi.objects.get(user_id=user,predmet_id=fk)
    if request.method == 'POST':
        form = profUpisiForm(request.POST, instance=upisi)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = profUpisiForm(instance=upisi)
    return render(request, 'projekti/editupis.html', {'form': form})

def listpred(request):
    predmeti=Predmeti.objects.all()
    context={'predmeti':predmeti}
    return render(request,'projekti/predstud.html',context)

def add_upis_student(request, pk):
    user = request.user 
    predmet = Predmeti.objects.get(id=pk)
    
    if request.method == 'POST':
        form = UpisForm(request.POST)
        print(form.errors)
        if form.is_valid():
            upis = form.save(commit=False)
            upis.user_id = user
            upis.predmet_id = predmet
            upis.save()
            return redirect('home')
    else:
        form = UpisForm(initial={'user_id': user, 'predmet_id': predmet})
        form.fields['user_id'].disabled = True
        form.fields['predmet_id'].disabled = True
        
    
    context = {'form': form}
    return render(request, 'projekti/addupisstud.html', context)

def current_upisi(request):
    user = request.user
    upisi = Upisi.objects.filter(user_id=user)
    context = {'upisi': upisi}
    return render(request, 'projekti/studupisi.html', context)

def delete_upis(request, upis_id):
    upis = get_object_or_404(Upisi, id=upis_id, status='up')

    if request.method == 'POST':
        upis.delete()
        return redirect('home')

    context = {'upis': upis}
    return render(request, 'projekti/delete_upis.html', context)

def delete_user(request, pk):
    user = Korisnik.objects.get(pk=pk)
    
    if request.method == 'POST':
        user.delete()
        return redirect('home')
    
    return render(request, 'projekti/delete_user.html', {'user': user})

def upis_studenta(request, student_id):
    user = Korisnik.objects.get(id=student_id)
    upisi = Upisi.objects.filter(user_id=student_id)
    ap_form = UpisForm(request.POST or None)
    
    if request.method == 'POST':
        if ap_form.is_valid():
            upis = ap_form.save(commit=False)
            passw = ap_form.cleaned_data['predmet_id']
            stat = ap_form.cleaned_data['status']
            upis.user_id = user
            upis.predmet_id = passw
            
            if user.status == 'red':
                predmeti = Predmeti.objects.filter(Q(sem_red=1) | Q(sem_red=2))
                for predmet in predmeti:
                    upis_obj = upisi.filter(predmet_id=predmet.id).first()
                    if upis_obj and upis_obj.status != 'pass':
                        return HttpResponse("Nije sve polozeno s 1. godine")
            
            elif user.status == 'izv':

projekt/templates/projekti/addUpisi.html
{% extends 'base.html' %}
{% block addUpisi %}
<form method="post">
        <h2>Upis studenta na predmet: </h2>
        {{data}}
    <br>
    <input type="submit" value="Potvrdi">
    {% csrf_token %}
</form>
{% endblock %}

projekt/templates/projekti/addpredmet.html
{%extends "projekti/main.html"%}
{%load crispy_forms_tags%}
{%block content%}
<div class="col-md-5">
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">
            Add predmet
        </legend>
        {{p_form|crispy}}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">
            Submit
        </button>
    </div>
</form>
</div>
{%endblock content%}

projekt/templates/projekti/addupisstud.html
{% extends 'projekti/main.html' %}
{% block content %}
<div class="col-md-5">
    <h5>Add Upis</h5>
    <br>
    <div class="card card-body">
        <form method="post">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_user_id">User ID</label>
                {{ form.user_id }}
            </div>
            
            <div class="form-group">
                <label for="id_predmet_id">Predmet ID</label>
                {{ form.predmet_id }}
            </div>
            
            <div class="form-group">
                <label for="id_status">Status</label>
                {{ form.status }}
            </div>
            
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

projekt/templates/projekti/editpredmet.html
{%extends "projekti/main.html"%}
{%load crispy_forms_tags%}
{%block content%}
<div class="col-md-5">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Edit Class
            </legend>
            {{eu_form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Submit
            </button>
        </div>
    </form>
</div>
{%endblock content%}

projekt/templates/projekti/editupis.html
{%extends "projekti/main.html"%}
{%load crispy_forms_tags%}
{%block content%}
<div class="col-md-5">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Edit Upis
            </legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Submit
            </button>
        </div>
    </form>
</div>
{%endblock content%}

projekt/templates/projekti/edituser.html
{%extends "projekti/main.html"%}
{%load crispy_forms_tags%}
{%block content%}
<div class="col-md-5">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Edit Zser
            </legend>
            {{eu_form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">
                Submit
            </button>
        </div>
    </form>
</div>
{%endblock content%}

projekt/templates/projekti/home.html
{%extends "projekti/main.html"%}
{%block content%}
    Welcome
{%endblock%}

projekt/templates/projekti/logout.html
{%extends "projekti/main.html"%}

{%block content%}
    <h2>you've logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                Log back in?
                <a class="ml-2" href="{% url 'login' %}">Log in again</a>
            </small>
        </div>
   
{% endblock content %}

projekt/templates/projekti/main.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css'%}">
</head>
<body>
    
    {% include 'projekti/navbar.html' %}

    {% block content %}

    {% endblock %}
    <hr>
    <h5>Footer</h5>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

projekt/templates/projekti/predstud.html
{% extends 'projekti/main.html' %}
{% block content %}
<div class="row">
    <div class="col-md-5">
        <br>
        <div class="card card-body">
            <table class="table table-sa">
                <tr>
                    <th>Name</th>
                    <th>Code</th>
                    <th>Semestar_red</th>
                    <th>Semestar_van</th>
                </tr>
                {% for predmet in predmeti %}
                <tr>
                    
                    <td>{{ predmet.name }}</td>
                    <td>{{ predmet.kod }}</td>
                    <td>{{predmet.sem_red}}</td>
                    <td>{{predmet.sem_izv}}</td>
                    <td><a class="btn btn-primary btn-sm btn-block" href ="{% url 'addupisstud' predmet.id %}">add upis</a></td>
                    
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

projekt/templates/projekti/profpred.html
{% extends 'projekti/main.html' %}
{% block content %}
<div class="row">
    <div class="col-md-5">
        <h5>Profesori</h5>
        <br>
        <div class="card card-body">
            <table class="table table-sa">
                <tr>
                    <th>Name</th>
                    <th>Code</th>
                </tr>
                {% for predmet in predmeti %}
                <tr>
                    
                    <td>{{ predmet.name }}</td>
                    <td>{{ predmet.kod }}</td>
                    <td><a class="btn btn-primary btn-sm btn-block" href ="{% url 'seestud' predmet.id %}">See students</a></td>
                    
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

projekt/templates/projekti/students.html
{%extends 'projekti/main.html'%}
{%block content  %}
<div class="col-md-5">
    <h5>Students</h5>
    <br>
    <div class="card card-body">
        
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Add upis</th>
                <th>See upis</th>
                <th>Delete student</th>
            </tr>
            {% for student in students %}
            <tr>
                <td><a class="btn btn-primary btn-sm " href ="{% url 'edituser' student.id %}">{{ student.username }}</a></td>
                <td><a class="btn btn-primary btn-sm btn-block" href ="{% url 'addupis' student.id %}">Add</a></td>
                <td><a class="btn btn-primary btn-sm " href ="{% url 'upis' student.id %}">Upisi</a></td>
                <td><a class="btn btn-primary btn-sm btn-block" href="{% url 'delete_user' student.id %}">Delete student</a></td>
                
                
            </tr>                   
            {% endfor %} 
        </table>
    </div>
</div>
{%endblock%}

projekt/templates/projekti/studpred.html
{% extends 'projekti/main.html' %}

{% block content %}
    <h3>Enrolled Students - {{ predmet.name }}</h3>
    <h4>Students who lost the signature:</h4>
    <ul>
        {% for upis in izgubili_potpis %}
            <li>{{ upis.user_id}}
                <div class="col-md-5">
                    <a class="btn btn-primary btn-sm btn-block" href ="{% url 'editupis' upis.user_id predmet.id %}">Edit upis</a>
              </div>
          </li>
        {% empty %}
            <li>No students </li>
        {% endfor %}
    </ul>

    <h4>Students who received the signature but have not passed:</h4>
    <ul>
        {% for upis in dobili_potpis %}
            <li>{{ upis.user_id }}
                <div class="col-md-5">
                      <a class="btn btn-primary btn-sm btn-block" href ="{% url 'editupis' upis.user_id predmet.id %}">Edit upis</a>
                </div>
            </li>
        {% empty %}
            <li>No students </li>
        {% endfor %}
    </ul>

    <h4>Students who passed the subject:</h4>
    <ul>
        {% for upis in polozili_predmet %}
            <li>{{ upis.user_id }}
                <div class="col-md-5">
                    <a class="btn btn-primary btn-sm btn-block" href ="{% url 'editupis' upis.user_id  predmet.id%}">Edit upis</a>
              </div>
          </li>
        {% empty %}
            <li>No students</li>
        {% endfor %}
    </ul>
{% endblock %}

projekt/templates/projekti/upisi.html
{% extends 'projekti/main.html' %}
{% block content %}
<div class="col-md-5">
    <h5>Upis</h5>
    <br>
    <div class="card card-body">
        <table class="table">
            <tr>
                <th>Upis</th>
            </tr>
            {% for upis in upisi %}
            <tr>
                <td>
                    <a class="btn btn-primary btn-sm btn-block" href="{% url 'editupis' upis.id %}">Edit Upis {{upis.predmet_id}}</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}